sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t nikoladragas/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nikoladragas/docker-react npm run test